In [113]:
'''          NUMPY Basics          '''

'          NUMPY Basics          '

In [13]:
''' Numpy
NumPy is a Python library. NumPy is used for working with arrays. NumPy is short for "Numerical Python".
It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
The array object in NumPy is called "ndarray", it provides a lot of supporting functions that make working with ndarray very easy.
Arrays are very frequently used in data science, where speed and resources are very important.

Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
This behavior is called locality of reference in computer science.
'''
#C:\Users\Your Name>pip install numpy --------> Installation

import numpy as np

#To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:
#arr = np.array([1, 2, 3, 4, 5]) #passing list
arr = np.array((1, 2, 3, 4, 5)) #passing tuple

print(arr)
print(np.__version__) # to check the version
print(type(arr)) #tells us the type of the object passed to it

arr = np.array(42) #0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
print(arr)

arr = np.array([1, 2, 3, 4, 5]) #An array with 0-D arrays as its elements is called uni-dimensional or 1-D array. These are the most common and basic arrays
print(arr)

arr = np.array([[1, 2, 3], [4, 5, 6]]) # An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors.
print(arr)

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) #These are often used to represent a 3rd order tensor.
print(arr)


a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim) #Check Number of Dimensions?
print(b.ndim)
print(c.ndim)
print(d.ndim)

'''Higher Dimensional Arrays
An array can have any number of dimensions. When the array is created, you can define the number of dimensions by using the "ndmin" argument.'''
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

'''In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, 
the 3rd dim has 1 element that is the matrix with the vector,
the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.'''

[1 2 3 4 5]
1.26.4
<class 'numpy.ndarray'>
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
0
1
2
3
[[[[[1 2 3 4]]]]]
number of dimensions : 5


'In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, \nthe 3rd dim has 1 element that is the matrix with the vector,\nthe 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.'

In [20]:
'''Access Array Elements
Array indexing is the same as accessing an array element.
The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.
'''
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[2] + arr[3])

# 2D Array accessing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

print('Last element from 2nd dim: ', arr[1, -1]) #Negative Indexing

# 3D Array accessing
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])

1
7
2nd element on 1st row:  2
5th element on 2nd row:  10
Last element from 2nd dim:  10
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [29]:
''' Slicing arrays
Slicing in python means taking elements from one given index to another given index.
We pass slice instead of index like this: [start:end].
We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0
If we don't pass end its considered length of array in that dimension
If we don't pass step its considered 1
'''
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) #includes 1 and excludes 5
print(arr[4:])
print(arr[:4])
print(arr[-3:-1]) # Negative slicing

print(arr[1:5:2])
print(arr[::2])

# 2D slicing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [47]:
''' Data Types in Python
By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j
'''

'''Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.
Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
'''

#The NumPy array object has a property called dtype that returns the data type of the array:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

#For i, u, f, S and U we can define size as well.
arr = np.array([1, 2, 3, 4], dtype='i4') #Create an array with data type 4 bytes integer:
print(arr)
print(arr.dtype)

#Converting Data Type on Existing Arrays-------> astype()
arr = np.array([1.1, 2.1, 3.1])
print(arr)
print(arr.dtype)

newarr = arr.astype('i') # 'f' or "float" for float, 'i' or "int" for integer etc.
print(newarr)
print(newarr.dtype)

newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

int32
[1 2 3 4]
int32
[1.1 2.1 3.1]
float64
[1 2 3]
int32
[ True  True  True]
bool


In [44]:
#A non integer string like 'a' can not be converted to integer (will raise an error):

#ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [51]:
''' NumPy Array Copy vs View ----------> Copy owns the data but not view'''
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy() #The copy SHOULD NOT be affected by the changes made to the original array.
arr[0] = 42

print(arr)
print(x)
#####################
x = arr.view() #The view SHOULD be affected by the changes made to the original array.
arr[0] = 42

print(arr)
print(x)
##########
x = arr.view()
x[0] = 31 #The original array SHOULD be affected by the changes made to the view.

print(arr)
print(x)

''' Check if Array Owns its Data
Every NumPy array has the attribute base that returns None if the array owns the data.
Otherwise, the base  attribute refers to the original object.
'''

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
[31  2  3  4  5]
[31  2  3  4  5]
None
[1 2 3 4 5]


In [53]:
''' Shape of an Array---->The shape of an array is the number of elements in each dimension.
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.'''
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape) # Returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [59]:
''' Reshaping arrays -----> Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension.'''

#Convert the following 1-D array with 12 elements into a 2-D array. The outermost dimension will have 4 arrays, each with 3 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

newarr = arr.reshape(2, 3, 2)
print(newarr)

print(arr.reshape(2, 6).base) #Check if the returned array is a copy or a view:

'''Unknown Dimension
You are allowed to have one "unknown" dimension.
Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
Pass -1 as the value, and NumPy will calculate this number for you.'''
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1) #Convert 1D array with 8 elements to 3D array with 2x2 elements:
print(newarr)

'''Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.
We can use reshape(-1) to do this.'''
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

#Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6]


In [67]:
'''Iterating Arrays
Iterating means going through elements one by one.
As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
If we iterate on a 1-D array it will go through each element one by one.'''
# 1D array (0 dimension)
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

# 2D
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

#If we iterate on a n-D array it will go through n-1th dimension one by one.

#To return the actual values, the scalars, we have to iterate the arrays in each dimension.
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

# 3D
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr: #In a 3-D array it will go through all the 2-D arrays.
  print(x)

for x in arr: #To return the actual values, the scalars, we have to iterate the arrays in each dimension.
  for y in x:
    for z in y:
      print(z)

#Iterating Arrays Using nditer()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

#Iterating Array With Different Data Types using op_dtypes 
'''NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action,
that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].'''
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

#Iterating With Different Step Size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
b'1'
b'2'
b'3'
1
3
5
7


In [69]:
''' Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.
Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.'''
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

# 2D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [77]:
'''Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.
In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.'''
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

# 2D array
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

''' Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.'''
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

#Stacking Along Rows
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

#Stacking Along Columns
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

#Stacking Along Height (depth)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [84]:
''' Splitting NumPy Arrays
Splitting is reverse operation of Joining.
Joining merges multiple arrays into one and Splitting breaks one array into multiple.
We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.'''
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

newarr = np.array_split(arr, 4) #adjusts accordingly
print(newarr)

#Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

#SPlitting 2D array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3) #The example above returns three 2-D arrays.
print(newarr)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]]) #Split the 2-D array into three 2-D arrays.
newarr = np.array_split(arr, 3)
print(newarr)

#In addition, you can specify which axis you want to do the split around.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

#An alternate solution is using hsplit() opposite of hstack()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

#Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [101]:
'''Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.
To search an array, use the where() method.'''
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

x = np.where(arr%2 == 0) #Find the indexes where the values are even:
print(x)

x = np.where(arr%2 == 1) #Find the indexes where the values are odd:
print(x)

'''Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index where
the specified value would be inserted to maintain the search order.'''
#The searchsorted() method is assumed to be used on sorted arrays.

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7) #Find the indexes where the value 7 should be inserted:
print(x)
'''Example explained: The number 7 should be inserted on index 1 to remain the sort order.
The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.'''

'''Search From the Right Side
By default the left most index is returned, but we can give side='right' to return the right most index instead.'''
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right') #Find the indexes where the value 7 should be inserted, starting from the right:
print(x)

#Find the indexes where the values 2, 4, and 6 should be inserted:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)
(array([0, 2, 4], dtype=int64),)
1
2
[1 2 3]


In [108]:
'''Sorting Arrays
Sorting means putting elements in an ordered sequence.
Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
The NumPy ndarray object has a function called sort(), that will sort a specified array.'''
arr = np.array([3, 2, 0, 1])
print(np.sort(arr)) #Note: This method returns a copy of the array, leaving the original array unchanged.
print(arr.base) #SO, it is a copy

arr = np.array(['banana', 'cherry', 'apple']) #You can also sort arrays of strings, or any other data type:
print(np.sort(arr))

#Sort Boolean 
arr = np.array([True, False, True])
print(np.sort(arr))

# Sort 2D array
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[0 1 2 3]
None
['apple' 'banana' 'cherry']
[False  True  True]
[[2 3 4]
 [0 1 5]]


In [111]:
'''Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.
In NumPy, you filter an array using a boolean index list.
A boolean index list is a list of booleans corresponding to indexes in the array.
If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.'''

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

#In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.
arr = np.array([41, 42, 43, 44])
filter_arr = [] # Create an empty list
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

#Creating Filter Directly From Array
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)


[41 43]
[False, False, True, True]
[43 44]
[False False  True  True]
[43 44]
